services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    restart: unless-stopped
